language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - '10'
  - '8'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
before_script:
  - find test -type d -exec chmod g+s {} \;
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]];
    then
      sudo chown root test/fixtures/not-owned/not-owned.txt;
      sudo chmod 666 test/fixtures/not-owned/not-owned.txt;
    fi
after_script:
  - npm run coveralls
